name: territories
description: A Flutter app for territories
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
